import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/AppShell";

export const Route = createFileRoute("/_authenticated/legal/terms")({
  head: () => ({ meta: [{ title: "Terms & Conditions — SLP Assist AI" }] }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <AppShell title="Terms & Conditions" back>
      <article className="space-y-4 rounded-2xl border border-border bg-card p-5 text-sm leading-relaxed shadow-card">
        <p className="text-muted-foreground">Last updated: July 2026</p>

        <Section title="Purpose">
          <p>
            SLP Assist AI is provided for educational and clinical decision
            support purposes only.
          </p>
        </Section>

        <Section title="AI-Generated Content">
          <p>
            Content generated by the AI may contain errors, omissions, or
            inaccuracies. The application does not provide medical diagnosis.
          </p>
        </Section>

        <Section title="Clinical Responsibility">
          <p>
            Users remain fully responsible for all clinical decisions. This app
            does not replace professional assessment, diagnosis, or treatment
            by a qualified Speech-Language Pathologist or Audiologist.
          </p>
        </Section>

        <Section title="Copyright">
          <p>
            All content, design, and materials are the copyright of SLP Assist
            AI. Users may not copy, reproduce, or redistribute app content
            without written permission.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            For questions regarding these terms, contact{" "}
            <a className="text-primary underline" href="mailto:slpassistai@gmail.com">
              slpassistai@gmail.com
            </a>
            .
          </p>
        </Section>
      </article>
    </AppShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="mb-2 text-sm font-semibold text-primary">{title}</h2>
      <div className="text-foreground/85">{children}</div>
    </section>
  );
}
