/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavedReportsRouteImport } from './routes/_authenticated/saved-reports'
import { Route as AuthenticatedNewCaseRouteImport } from './routes/_authenticated/new-case'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedAdminDebugRouteImport } from './routes/_authenticated/admin-debug'
import { Route as AuthenticatedCaseIdRouteImport } from './routes/_authenticated/case.$id'
import { Route as AuthenticatedCaseIdEditRouteImport } from './routes/_authenticated/case.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedReportsRoute =
  AuthenticatedSavedReportsRouteImport.update({
    id: '/saved-reports',
    path: '/saved-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewCaseRoute = AuthenticatedNewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDebugRoute = AuthenticatedAdminDebugRouteImport.update({
  id: '/admin-debug',
  path: '/admin-debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaseIdRoute = AuthenticatedCaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaseIdEditRoute = AuthenticatedCaseIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthenticatedCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-debug': typeof AuthenticatedAdminDebugRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/games': typeof AuthenticatedGamesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new-case': typeof AuthenticatedNewCaseRoute
  '/saved-reports': typeof AuthenticatedSavedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/case/$id': typeof AuthenticatedCaseIdRouteWithChildren
  '/case/$id/edit': typeof AuthenticatedCaseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-debug': typeof AuthenticatedAdminDebugRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/games': typeof AuthenticatedGamesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/new-case': typeof AuthenticatedNewCaseRoute
  '/saved-reports': typeof AuthenticatedSavedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/case/$id': typeof AuthenticatedCaseIdRouteWithChildren
  '/case/$id/edit': typeof AuthenticatedCaseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin-debug': typeof AuthenticatedAdminDebugRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/new-case': typeof AuthenticatedNewCaseRoute
  '/_authenticated/saved-reports': typeof AuthenticatedSavedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/case/$id': typeof AuthenticatedCaseIdRouteWithChildren
  '/_authenticated/case/$id/edit': typeof AuthenticatedCaseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin-debug'
    | '/cases'
    | '/games'
    | '/home'
    | '/knowledge'
    | '/library'
    | '/new-case'
    | '/saved-reports'
    | '/settings'
    | '/case/$id'
    | '/case/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin-debug'
    | '/cases'
    | '/games'
    | '/home'
    | '/knowledge'
    | '/library'
    | '/new-case'
    | '/saved-reports'
    | '/settings'
    | '/case/$id'
    | '/case/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin-debug'
    | '/_authenticated/cases'
    | '/_authenticated/games'
    | '/_authenticated/home'
    | '/_authenticated/knowledge'
    | '/_authenticated/library'
    | '/_authenticated/new-case'
    | '/_authenticated/saved-reports'
    | '/_authenticated/settings'
    | '/_authenticated/case/$id'
    | '/_authenticated/case/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved-reports': {
      id: '/_authenticated/saved-reports'
      path: '/saved-reports'
      fullPath: '/saved-reports'
      preLoaderRoute: typeof AuthenticatedSavedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-case': {
      id: '/_authenticated/new-case'
      path: '/new-case'
      fullPath: '/new-case'
      preLoaderRoute: typeof AuthenticatedNewCaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-debug': {
      id: '/_authenticated/admin-debug'
      path: '/admin-debug'
      fullPath: '/admin-debug'
      preLoaderRoute: typeof AuthenticatedAdminDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/case/$id': {
      id: '/_authenticated/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof AuthenticatedCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/case/$id/edit': {
      id: '/_authenticated/case/$id/edit'
      path: '/edit'
      fullPath: '/case/$id/edit'
      preLoaderRoute: typeof AuthenticatedCaseIdEditRouteImport
      parentRoute: typeof AuthenticatedCaseIdRoute
    }
  }
}

interface AuthenticatedCaseIdRouteChildren {
  AuthenticatedCaseIdEditRoute: typeof AuthenticatedCaseIdEditRoute
}

const AuthenticatedCaseIdRouteChildren: AuthenticatedCaseIdRouteChildren = {
  AuthenticatedCaseIdEditRoute: AuthenticatedCaseIdEditRoute,
}

const AuthenticatedCaseIdRouteWithChildren =
  AuthenticatedCaseIdRoute._addFileChildren(AuthenticatedCaseIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDebugRoute: typeof AuthenticatedAdminDebugRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedNewCaseRoute: typeof AuthenticatedNewCaseRoute
  AuthenticatedSavedReportsRoute: typeof AuthenticatedSavedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCaseIdRoute: typeof AuthenticatedCaseIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDebugRoute: AuthenticatedAdminDebugRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedNewCaseRoute: AuthenticatedNewCaseRoute,
  AuthenticatedSavedReportsRoute: AuthenticatedSavedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCaseIdRoute: AuthenticatedCaseIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
