/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiAacGenerateImageRouteImport } from './routes/api/aac-generate-image'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavedReportsRouteImport } from './routes/_authenticated/saved-reports'
import { Route as AuthenticatedNewCaseRouteImport } from './routes/_authenticated/new-case'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedAdminDebugRouteImport } from './routes/_authenticated/admin-debug'
import { Route as AuthenticatedLibraryIndexRouteImport } from './routes/_authenticated/library.index'
import { Route as AuthenticatedClinicalToolsIndexRouteImport } from './routes/_authenticated/clinical-tools.index'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account.delete'
import { Route as AuthenticatedLibraryUploadsRouteImport } from './routes/_authenticated/library.uploads'
import { Route as AuthenticatedLibraryResearchRouteImport } from './routes/_authenticated/library.research'
import { Route as AuthenticatedLibraryDownloadsRouteImport } from './routes/_authenticated/library.downloads'
import { Route as AuthenticatedLibraryCommunityRouteImport } from './routes/_authenticated/library.community'
import { Route as AuthenticatedLibraryCaseHistoryRouteImport } from './routes/_authenticated/library.case-history'
import { Route as AuthenticatedLibraryBooksRouteImport } from './routes/_authenticated/library.books'
import { Route as AuthenticatedLibraryAppReferenceRouteImport } from './routes/_authenticated/library.app-reference'
import { Route as AuthenticatedLegalTermsRouteImport } from './routes/_authenticated/legal.terms'
import { Route as AuthenticatedLegalPrivacyRouteImport } from './routes/_authenticated/legal.privacy'
import { Route as AuthenticatedLegalDisclaimerRouteImport } from './routes/_authenticated/legal.disclaimer'
import { Route as AuthenticatedLegalAccountDeletionRouteImport } from './routes/_authenticated/legal.account-deletion'
import { Route as AuthenticatedClinicalToolsVoiceAnalysisRouteImport } from './routes/_authenticated/clinical-tools.voice-analysis'
import { Route as AuthenticatedClinicalToolsAacRouteImport } from './routes/_authenticated/clinical-tools.aac'
import { Route as AuthenticatedCaseIdRouteImport } from './routes/_authenticated/case.$id'
import { Route as AuthenticatedCaseIdEditRouteImport } from './routes/_authenticated/case.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAacGenerateImageRoute = ApiAacGenerateImageRouteImport.update({
  id: '/api/aac-generate-image',
  path: '/api/aac-generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedReportsRoute =
  AuthenticatedSavedReportsRouteImport.update({
    id: '/saved-reports',
    path: '/saved-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewCaseRoute = AuthenticatedNewCaseRouteImport.update({
  id: '/new-case',
  path: '/new-case',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDebugRoute = AuthenticatedAdminDebugRouteImport.update({
  id: '/admin-debug',
  path: '/admin-debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryIndexRoute =
  AuthenticatedLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedClinicalToolsIndexRoute =
  AuthenticatedClinicalToolsIndexRouteImport.update({
    id: '/clinical-tools/',
    path: '/clinical-tools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryUploadsRoute =
  AuthenticatedLibraryUploadsRouteImport.update({
    id: '/uploads',
    path: '/uploads',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryResearchRoute =
  AuthenticatedLibraryResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryDownloadsRoute =
  AuthenticatedLibraryDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryCommunityRoute =
  AuthenticatedLibraryCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryCaseHistoryRoute =
  AuthenticatedLibraryCaseHistoryRouteImport.update({
    id: '/case-history',
    path: '/case-history',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryBooksRoute =
  AuthenticatedLibraryBooksRouteImport.update({
    id: '/books',
    path: '/books',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryAppReferenceRoute =
  AuthenticatedLibraryAppReferenceRouteImport.update({
    id: '/app-reference',
    path: '/app-reference',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLegalTermsRoute = AuthenticatedLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLegalPrivacyRoute =
  AuthenticatedLegalPrivacyRouteImport.update({
    id: '/legal/privacy',
    path: '/legal/privacy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegalDisclaimerRoute =
  AuthenticatedLegalDisclaimerRouteImport.update({
    id: '/legal/disclaimer',
    path: '/legal/disclaimer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegalAccountDeletionRoute =
  AuthenticatedLegalAccountDeletionRouteImport.update({
    id: '/legal/account-deletion',
    path: '/legal/account-deletion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicalToolsVoiceAnalysisRoute =
  AuthenticatedClinicalToolsVoiceAnalysisRouteImport.update({
    id: '/clinical-tools/voice-analysis',
    path: '/clinical-tools/voice-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClinicalToolsAacRoute =
  AuthenticatedClinicalToolsAacRouteImport.update({
    id: '/clinical-tools/aac',
    path: '/clinical-tools/aac',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaseIdRoute = AuthenticatedCaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCaseIdEditRoute = AuthenticatedCaseIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthenticatedCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-debug': typeof AuthenticatedAdminDebugRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/games': typeof AuthenticatedGamesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/new-case': typeof AuthenticatedNewCaseRoute
  '/saved-reports': typeof AuthenticatedSavedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/aac-generate-image': typeof ApiAacGenerateImageRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/case/$id': typeof AuthenticatedCaseIdRouteWithChildren
  '/clinical-tools/aac': typeof AuthenticatedClinicalToolsAacRoute
  '/clinical-tools/voice-analysis': typeof AuthenticatedClinicalToolsVoiceAnalysisRoute
  '/legal/account-deletion': typeof AuthenticatedLegalAccountDeletionRoute
  '/legal/disclaimer': typeof AuthenticatedLegalDisclaimerRoute
  '/legal/privacy': typeof AuthenticatedLegalPrivacyRoute
  '/legal/terms': typeof AuthenticatedLegalTermsRoute
  '/library/app-reference': typeof AuthenticatedLibraryAppReferenceRoute
  '/library/books': typeof AuthenticatedLibraryBooksRoute
  '/library/case-history': typeof AuthenticatedLibraryCaseHistoryRoute
  '/library/community': typeof AuthenticatedLibraryCommunityRoute
  '/library/downloads': typeof AuthenticatedLibraryDownloadsRoute
  '/library/research': typeof AuthenticatedLibraryResearchRoute
  '/library/uploads': typeof AuthenticatedLibraryUploadsRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/clinical-tools/': typeof AuthenticatedClinicalToolsIndexRoute
  '/library/': typeof AuthenticatedLibraryIndexRoute
  '/case/$id/edit': typeof AuthenticatedCaseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-debug': typeof AuthenticatedAdminDebugRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/games': typeof AuthenticatedGamesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/new-case': typeof AuthenticatedNewCaseRoute
  '/saved-reports': typeof AuthenticatedSavedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/aac-generate-image': typeof ApiAacGenerateImageRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/case/$id': typeof AuthenticatedCaseIdRouteWithChildren
  '/clinical-tools/aac': typeof AuthenticatedClinicalToolsAacRoute
  '/clinical-tools/voice-analysis': typeof AuthenticatedClinicalToolsVoiceAnalysisRoute
  '/legal/account-deletion': typeof AuthenticatedLegalAccountDeletionRoute
  '/legal/disclaimer': typeof AuthenticatedLegalDisclaimerRoute
  '/legal/privacy': typeof AuthenticatedLegalPrivacyRoute
  '/legal/terms': typeof AuthenticatedLegalTermsRoute
  '/library/app-reference': typeof AuthenticatedLibraryAppReferenceRoute
  '/library/books': typeof AuthenticatedLibraryBooksRoute
  '/library/case-history': typeof AuthenticatedLibraryCaseHistoryRoute
  '/library/community': typeof AuthenticatedLibraryCommunityRoute
  '/library/downloads': typeof AuthenticatedLibraryDownloadsRoute
  '/library/research': typeof AuthenticatedLibraryResearchRoute
  '/library/uploads': typeof AuthenticatedLibraryUploadsRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/clinical-tools': typeof AuthenticatedClinicalToolsIndexRoute
  '/library': typeof AuthenticatedLibraryIndexRoute
  '/case/$id/edit': typeof AuthenticatedCaseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin-debug': typeof AuthenticatedAdminDebugRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/new-case': typeof AuthenticatedNewCaseRoute
  '/_authenticated/saved-reports': typeof AuthenticatedSavedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/aac-generate-image': typeof ApiAacGenerateImageRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/_authenticated/case/$id': typeof AuthenticatedCaseIdRouteWithChildren
  '/_authenticated/clinical-tools/aac': typeof AuthenticatedClinicalToolsAacRoute
  '/_authenticated/clinical-tools/voice-analysis': typeof AuthenticatedClinicalToolsVoiceAnalysisRoute
  '/_authenticated/legal/account-deletion': typeof AuthenticatedLegalAccountDeletionRoute
  '/_authenticated/legal/disclaimer': typeof AuthenticatedLegalDisclaimerRoute
  '/_authenticated/legal/privacy': typeof AuthenticatedLegalPrivacyRoute
  '/_authenticated/legal/terms': typeof AuthenticatedLegalTermsRoute
  '/_authenticated/library/app-reference': typeof AuthenticatedLibraryAppReferenceRoute
  '/_authenticated/library/books': typeof AuthenticatedLibraryBooksRoute
  '/_authenticated/library/case-history': typeof AuthenticatedLibraryCaseHistoryRoute
  '/_authenticated/library/community': typeof AuthenticatedLibraryCommunityRoute
  '/_authenticated/library/downloads': typeof AuthenticatedLibraryDownloadsRoute
  '/_authenticated/library/research': typeof AuthenticatedLibraryResearchRoute
  '/_authenticated/library/uploads': typeof AuthenticatedLibraryUploadsRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/_authenticated/clinical-tools/': typeof AuthenticatedClinicalToolsIndexRoute
  '/_authenticated/library/': typeof AuthenticatedLibraryIndexRoute
  '/_authenticated/case/$id/edit': typeof AuthenticatedCaseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin-debug'
    | '/cases'
    | '/games'
    | '/home'
    | '/knowledge'
    | '/library'
    | '/new-case'
    | '/saved-reports'
    | '/settings'
    | '/api/aac-generate-image'
    | '/api/analyze'
    | '/case/$id'
    | '/clinical-tools/aac'
    | '/clinical-tools/voice-analysis'
    | '/legal/account-deletion'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/library/app-reference'
    | '/library/books'
    | '/library/case-history'
    | '/library/community'
    | '/library/downloads'
    | '/library/research'
    | '/library/uploads'
    | '/api/account/delete'
    | '/clinical-tools/'
    | '/library/'
    | '/case/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin-debug'
    | '/cases'
    | '/games'
    | '/home'
    | '/knowledge'
    | '/new-case'
    | '/saved-reports'
    | '/settings'
    | '/api/aac-generate-image'
    | '/api/analyze'
    | '/case/$id'
    | '/clinical-tools/aac'
    | '/clinical-tools/voice-analysis'
    | '/legal/account-deletion'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/library/app-reference'
    | '/library/books'
    | '/library/case-history'
    | '/library/community'
    | '/library/downloads'
    | '/library/research'
    | '/library/uploads'
    | '/api/account/delete'
    | '/clinical-tools'
    | '/library'
    | '/case/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin-debug'
    | '/_authenticated/cases'
    | '/_authenticated/games'
    | '/_authenticated/home'
    | '/_authenticated/knowledge'
    | '/_authenticated/library'
    | '/_authenticated/new-case'
    | '/_authenticated/saved-reports'
    | '/_authenticated/settings'
    | '/api/aac-generate-image'
    | '/api/analyze'
    | '/_authenticated/case/$id'
    | '/_authenticated/clinical-tools/aac'
    | '/_authenticated/clinical-tools/voice-analysis'
    | '/_authenticated/legal/account-deletion'
    | '/_authenticated/legal/disclaimer'
    | '/_authenticated/legal/privacy'
    | '/_authenticated/legal/terms'
    | '/_authenticated/library/app-reference'
    | '/_authenticated/library/books'
    | '/_authenticated/library/case-history'
    | '/_authenticated/library/community'
    | '/_authenticated/library/downloads'
    | '/_authenticated/library/research'
    | '/_authenticated/library/uploads'
    | '/api/account/delete'
    | '/_authenticated/clinical-tools/'
    | '/_authenticated/library/'
    | '/_authenticated/case/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAacGenerateImageRoute: typeof ApiAacGenerateImageRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aac-generate-image': {
      id: '/api/aac-generate-image'
      path: '/api/aac-generate-image'
      fullPath: '/api/aac-generate-image'
      preLoaderRoute: typeof ApiAacGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved-reports': {
      id: '/_authenticated/saved-reports'
      path: '/saved-reports'
      fullPath: '/saved-reports'
      preLoaderRoute: typeof AuthenticatedSavedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-case': {
      id: '/_authenticated/new-case'
      path: '/new-case'
      fullPath: '/new-case'
      preLoaderRoute: typeof AuthenticatedNewCaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-debug': {
      id: '/_authenticated/admin-debug'
      path: '/admin-debug'
      fullPath: '/admin-debug'
      preLoaderRoute: typeof AuthenticatedAdminDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/': {
      id: '/_authenticated/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/clinical-tools/': {
      id: '/_authenticated/clinical-tools/'
      path: '/clinical-tools'
      fullPath: '/clinical-tools/'
      preLoaderRoute: typeof AuthenticatedClinicalToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library/uploads': {
      id: '/_authenticated/library/uploads'
      path: '/uploads'
      fullPath: '/library/uploads'
      preLoaderRoute: typeof AuthenticatedLibraryUploadsRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/research': {
      id: '/_authenticated/library/research'
      path: '/research'
      fullPath: '/library/research'
      preLoaderRoute: typeof AuthenticatedLibraryResearchRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/downloads': {
      id: '/_authenticated/library/downloads'
      path: '/downloads'
      fullPath: '/library/downloads'
      preLoaderRoute: typeof AuthenticatedLibraryDownloadsRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/community': {
      id: '/_authenticated/library/community'
      path: '/community'
      fullPath: '/library/community'
      preLoaderRoute: typeof AuthenticatedLibraryCommunityRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/case-history': {
      id: '/_authenticated/library/case-history'
      path: '/case-history'
      fullPath: '/library/case-history'
      preLoaderRoute: typeof AuthenticatedLibraryCaseHistoryRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/books': {
      id: '/_authenticated/library/books'
      path: '/books'
      fullPath: '/library/books'
      preLoaderRoute: typeof AuthenticatedLibraryBooksRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/app-reference': {
      id: '/_authenticated/library/app-reference'
      path: '/app-reference'
      fullPath: '/library/app-reference'
      preLoaderRoute: typeof AuthenticatedLibraryAppReferenceRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/legal/terms': {
      id: '/_authenticated/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof AuthenticatedLegalTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal/privacy': {
      id: '/_authenticated/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof AuthenticatedLegalPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal/disclaimer': {
      id: '/_authenticated/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof AuthenticatedLegalDisclaimerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal/account-deletion': {
      id: '/_authenticated/legal/account-deletion'
      path: '/legal/account-deletion'
      fullPath: '/legal/account-deletion'
      preLoaderRoute: typeof AuthenticatedLegalAccountDeletionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinical-tools/voice-analysis': {
      id: '/_authenticated/clinical-tools/voice-analysis'
      path: '/clinical-tools/voice-analysis'
      fullPath: '/clinical-tools/voice-analysis'
      preLoaderRoute: typeof AuthenticatedClinicalToolsVoiceAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinical-tools/aac': {
      id: '/_authenticated/clinical-tools/aac'
      path: '/clinical-tools/aac'
      fullPath: '/clinical-tools/aac'
      preLoaderRoute: typeof AuthenticatedClinicalToolsAacRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/case/$id': {
      id: '/_authenticated/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof AuthenticatedCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/case/$id/edit': {
      id: '/_authenticated/case/$id/edit'
      path: '/edit'
      fullPath: '/case/$id/edit'
      preLoaderRoute: typeof AuthenticatedCaseIdEditRouteImport
      parentRoute: typeof AuthenticatedCaseIdRoute
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryAppReferenceRoute: typeof AuthenticatedLibraryAppReferenceRoute
  AuthenticatedLibraryBooksRoute: typeof AuthenticatedLibraryBooksRoute
  AuthenticatedLibraryCaseHistoryRoute: typeof AuthenticatedLibraryCaseHistoryRoute
  AuthenticatedLibraryCommunityRoute: typeof AuthenticatedLibraryCommunityRoute
  AuthenticatedLibraryDownloadsRoute: typeof AuthenticatedLibraryDownloadsRoute
  AuthenticatedLibraryResearchRoute: typeof AuthenticatedLibraryResearchRoute
  AuthenticatedLibraryUploadsRoute: typeof AuthenticatedLibraryUploadsRoute
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryAppReferenceRoute: AuthenticatedLibraryAppReferenceRoute,
  AuthenticatedLibraryBooksRoute: AuthenticatedLibraryBooksRoute,
  AuthenticatedLibraryCaseHistoryRoute: AuthenticatedLibraryCaseHistoryRoute,
  AuthenticatedLibraryCommunityRoute: AuthenticatedLibraryCommunityRoute,
  AuthenticatedLibraryDownloadsRoute: AuthenticatedLibraryDownloadsRoute,
  AuthenticatedLibraryResearchRoute: AuthenticatedLibraryResearchRoute,
  AuthenticatedLibraryUploadsRoute: AuthenticatedLibraryUploadsRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedCaseIdRouteChildren {
  AuthenticatedCaseIdEditRoute: typeof AuthenticatedCaseIdEditRoute
}

const AuthenticatedCaseIdRouteChildren: AuthenticatedCaseIdRouteChildren = {
  AuthenticatedCaseIdEditRoute: AuthenticatedCaseIdEditRoute,
}

const AuthenticatedCaseIdRouteWithChildren =
  AuthenticatedCaseIdRoute._addFileChildren(AuthenticatedCaseIdRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDebugRoute: typeof AuthenticatedAdminDebugRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedNewCaseRoute: typeof AuthenticatedNewCaseRoute
  AuthenticatedSavedReportsRoute: typeof AuthenticatedSavedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCaseIdRoute: typeof AuthenticatedCaseIdRouteWithChildren
  AuthenticatedClinicalToolsAacRoute: typeof AuthenticatedClinicalToolsAacRoute
  AuthenticatedClinicalToolsVoiceAnalysisRoute: typeof AuthenticatedClinicalToolsVoiceAnalysisRoute
  AuthenticatedLegalAccountDeletionRoute: typeof AuthenticatedLegalAccountDeletionRoute
  AuthenticatedLegalDisclaimerRoute: typeof AuthenticatedLegalDisclaimerRoute
  AuthenticatedLegalPrivacyRoute: typeof AuthenticatedLegalPrivacyRoute
  AuthenticatedLegalTermsRoute: typeof AuthenticatedLegalTermsRoute
  AuthenticatedClinicalToolsIndexRoute: typeof AuthenticatedClinicalToolsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDebugRoute: AuthenticatedAdminDebugRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedNewCaseRoute: AuthenticatedNewCaseRoute,
  AuthenticatedSavedReportsRoute: AuthenticatedSavedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCaseIdRoute: AuthenticatedCaseIdRouteWithChildren,
  AuthenticatedClinicalToolsAacRoute: AuthenticatedClinicalToolsAacRoute,
  AuthenticatedClinicalToolsVoiceAnalysisRoute:
    AuthenticatedClinicalToolsVoiceAnalysisRoute,
  AuthenticatedLegalAccountDeletionRoute:
    AuthenticatedLegalAccountDeletionRoute,
  AuthenticatedLegalDisclaimerRoute: AuthenticatedLegalDisclaimerRoute,
  AuthenticatedLegalPrivacyRoute: AuthenticatedLegalPrivacyRoute,
  AuthenticatedLegalTermsRoute: AuthenticatedLegalTermsRoute,
  AuthenticatedClinicalToolsIndexRoute: AuthenticatedClinicalToolsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAacGenerateImageRoute: ApiAacGenerateImageRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
